# CMake generated Testfile for 
# Source directory: C:/Users/kai99/Desktop/NEXUS
# Build directory: C:/Users/kai99/Desktop/NEXUS/build-release
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_arena_rollback]=] "C:/Users/kai99/Desktop/NEXUS/build-release/test_arena_rollback.exe")
set_tests_properties([=[test_arena_rollback]=] PROPERTIES  TIMEOUT "60" WORKING_DIRECTORY "C:/Users/kai99/Desktop/NEXUS" _BACKTRACE_TRIPLES "C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;116;add_test;C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;0;")
add_test([=[test_arena_rollback_shared]=] "C:/Users/kai99/Desktop/NEXUS/build-release/test_arena_rollback_shared.exe")
set_tests_properties([=[test_arena_rollback_shared]=] PROPERTIES  TIMEOUT "60" WORKING_DIRECTORY "C:/Users/kai99/Desktop/NEXUS" _BACKTRACE_TRIPLES "C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;124;add_test;C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;0;")
add_test([=[test_bitmap]=] "C:/Users/kai99/Desktop/NEXUS/build-release/test_bitmap.exe")
set_tests_properties([=[test_bitmap]=] PROPERTIES  TIMEOUT "60" WORKING_DIRECTORY "C:/Users/kai99/Desktop/NEXUS" _BACKTRACE_TRIPLES "C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;116;add_test;C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;0;")
add_test([=[test_bitmap_shared]=] "C:/Users/kai99/Desktop/NEXUS/build-release/test_bitmap_shared.exe")
set_tests_properties([=[test_bitmap_shared]=] PROPERTIES  TIMEOUT "60" WORKING_DIRECTORY "C:/Users/kai99/Desktop/NEXUS" _BACKTRACE_TRIPLES "C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;124;add_test;C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;0;")
add_test([=[test_core]=] "C:/Users/kai99/Desktop/NEXUS/build-release/test_core.exe")
set_tests_properties([=[test_core]=] PROPERTIES  TIMEOUT "60" WORKING_DIRECTORY "C:/Users/kai99/Desktop/NEXUS" _BACKTRACE_TRIPLES "C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;116;add_test;C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;0;")
add_test([=[test_core_shared]=] "C:/Users/kai99/Desktop/NEXUS/build-release/test_core_shared.exe")
set_tests_properties([=[test_core_shared]=] PROPERTIES  TIMEOUT "60" WORKING_DIRECTORY "C:/Users/kai99/Desktop/NEXUS" _BACKTRACE_TRIPLES "C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;124;add_test;C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;0;")
add_test([=[test_fuzzy]=] "C:/Users/kai99/Desktop/NEXUS/build-release/test_fuzzy.exe")
set_tests_properties([=[test_fuzzy]=] PROPERTIES  TIMEOUT "60" WORKING_DIRECTORY "C:/Users/kai99/Desktop/NEXUS" _BACKTRACE_TRIPLES "C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;116;add_test;C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;0;")
add_test([=[test_fuzzy_shared]=] "C:/Users/kai99/Desktop/NEXUS/build-release/test_fuzzy_shared.exe")
set_tests_properties([=[test_fuzzy_shared]=] PROPERTIES  TIMEOUT "60" WORKING_DIRECTORY "C:/Users/kai99/Desktop/NEXUS" _BACKTRACE_TRIPLES "C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;124;add_test;C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;0;")
add_test([=[test_json]=] "C:/Users/kai99/Desktop/NEXUS/build-release/test_json.exe")
set_tests_properties([=[test_json]=] PROPERTIES  TIMEOUT "60" WORKING_DIRECTORY "C:/Users/kai99/Desktop/NEXUS" _BACKTRACE_TRIPLES "C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;116;add_test;C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;0;")
add_test([=[test_json_shared]=] "C:/Users/kai99/Desktop/NEXUS/build-release/test_json_shared.exe")
set_tests_properties([=[test_json_shared]=] PROPERTIES  TIMEOUT "60" WORKING_DIRECTORY "C:/Users/kai99/Desktop/NEXUS" _BACKTRACE_TRIPLES "C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;124;add_test;C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;0;")
add_test([=[test_parse]=] "C:/Users/kai99/Desktop/NEXUS/build-release/test_parse.exe")
set_tests_properties([=[test_parse]=] PROPERTIES  TIMEOUT "60" WORKING_DIRECTORY "C:/Users/kai99/Desktop/NEXUS" _BACKTRACE_TRIPLES "C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;116;add_test;C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;0;")
add_test([=[test_parse_shared]=] "C:/Users/kai99/Desktop/NEXUS/build-release/test_parse_shared.exe")
set_tests_properties([=[test_parse_shared]=] PROPERTIES  TIMEOUT "60" WORKING_DIRECTORY "C:/Users/kai99/Desktop/NEXUS" _BACKTRACE_TRIPLES "C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;124;add_test;C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;0;")
add_test([=[test_platform]=] "C:/Users/kai99/Desktop/NEXUS/build-release/test_platform.exe")
set_tests_properties([=[test_platform]=] PROPERTIES  TIMEOUT "60" WORKING_DIRECTORY "C:/Users/kai99/Desktop/NEXUS" _BACKTRACE_TRIPLES "C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;116;add_test;C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;0;")
add_test([=[test_platform_shared]=] "C:/Users/kai99/Desktop/NEXUS/build-release/test_platform_shared.exe")
set_tests_properties([=[test_platform_shared]=] PROPERTIES  TIMEOUT "60" WORKING_DIRECTORY "C:/Users/kai99/Desktop/NEXUS" _BACKTRACE_TRIPLES "C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;124;add_test;C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;0;")
add_test([=[test_regex]=] "C:/Users/kai99/Desktop/NEXUS/build-release/test_regex.exe")
set_tests_properties([=[test_regex]=] PROPERTIES  TIMEOUT "60" WORKING_DIRECTORY "C:/Users/kai99/Desktop/NEXUS" _BACKTRACE_TRIPLES "C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;116;add_test;C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;0;")
add_test([=[test_regex_shared]=] "C:/Users/kai99/Desktop/NEXUS/build-release/test_regex_shared.exe")
set_tests_properties([=[test_regex_shared]=] PROPERTIES  TIMEOUT "60" WORKING_DIRECTORY "C:/Users/kai99/Desktop/NEXUS" _BACKTRACE_TRIPLES "C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;124;add_test;C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;0;")
add_test([=[test_simd]=] "C:/Users/kai99/Desktop/NEXUS/build-release/test_simd.exe")
set_tests_properties([=[test_simd]=] PROPERTIES  TIMEOUT "60" WORKING_DIRECTORY "C:/Users/kai99/Desktop/NEXUS" _BACKTRACE_TRIPLES "C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;116;add_test;C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;0;")
add_test([=[test_simd_shared]=] "C:/Users/kai99/Desktop/NEXUS/build-release/test_simd_shared.exe")
set_tests_properties([=[test_simd_shared]=] PROPERTIES  TIMEOUT "60" WORKING_DIRECTORY "C:/Users/kai99/Desktop/NEXUS" _BACKTRACE_TRIPLES "C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;124;add_test;C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;0;")
add_test([=[test_utf8]=] "C:/Users/kai99/Desktop/NEXUS/build-release/test_utf8.exe")
set_tests_properties([=[test_utf8]=] PROPERTIES  TIMEOUT "60" WORKING_DIRECTORY "C:/Users/kai99/Desktop/NEXUS" _BACKTRACE_TRIPLES "C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;116;add_test;C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;0;")
add_test([=[test_utf8_shared]=] "C:/Users/kai99/Desktop/NEXUS/build-release/test_utf8_shared.exe")
set_tests_properties([=[test_utf8_shared]=] PROPERTIES  TIMEOUT "60" WORKING_DIRECTORY "C:/Users/kai99/Desktop/NEXUS" _BACKTRACE_TRIPLES "C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;124;add_test;C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;0;")
add_test([=[test_vec]=] "C:/Users/kai99/Desktop/NEXUS/build-release/test_vec.exe")
set_tests_properties([=[test_vec]=] PROPERTIES  TIMEOUT "60" WORKING_DIRECTORY "C:/Users/kai99/Desktop/NEXUS" _BACKTRACE_TRIPLES "C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;116;add_test;C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;0;")
add_test([=[test_vec_shared]=] "C:/Users/kai99/Desktop/NEXUS/build-release/test_vec_shared.exe")
set_tests_properties([=[test_vec_shared]=] PROPERTIES  TIMEOUT "60" WORKING_DIRECTORY "C:/Users/kai99/Desktop/NEXUS" _BACKTRACE_TRIPLES "C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;124;add_test;C:/Users/kai99/Desktop/NEXUS/CMakeLists.txt;0;")
